---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml

  roles:
    - role: geerlingguy.homebrew
    - role: geerlingguy.mas

  tasks:
    - name: Copy fonts
      copy:
        src: templates/fonts/Roboto Mono Medium for Powerline.ttf
        dest: /Library/Fonts

    - name: Run .macos
      shell:
        cmd: "./.macos --no-restart"
        chdir: templates
      changed_when: false

    - name: Add dotfiles
      import_tasks: tasks/oh-my-zsh.yml

    - name: Check that ruby 2.5.1 installed
      shell: rbenv versions
      register: rbenv_versions
      changed_when: false

    - name: install ruby
      shell: "rbenv install 2.5.1"
      when: rbenv_versions.stdout.find("2.5.1") == -1

    - name: set default ruby
      shell: "rbenv global 2.5.1"
      when: rbenv_versions.stdout.find("* 2.5.1") != -1
