---
- name: Check that oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: stat_result

- name: Install oh my zsh
  shell: 'curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh'
  when: stat_result.stat.exists == False

- name: Copy dotfiles
  copy:
    src: "templates/dotfiles/{{ item }}"
    dest: ~/
  with_list:
    - .aliases
    - .gemrc
    - .gitconfig
    - .gitignore
    - .zsh_custom

- name: Add custom zsh settings
  lineinfile:
    path: ~/.zshrc
    line: '. ~/.zsh_custom'

- name: Set zsh theme
  lineinfile:
    path: ~/.zshrc
    regexp: '^ZSH_THEME='
    line: 'ZSH_THEME="agnoster"'

- name: Set zsh plugins
  lineinfile:
    path: ~/.zshrc
    regexp: '^plugins='
    line: 'plugins=(git)'
