---
- name: Copy dotfiles
  copy:
    src: "{{ item }}"
    dest: ~/
  with_fileglob:
    - templates/dotfiles/*

- name: Add custom zsh settings
  lineinfile:
    path: ~/.zshrc
    line: '. ~/.zsh_custom'

- name: Set zsh theme
  lineinfile:
    path: ~/.zshrc
    regexp: '^ZSH_THEME='
    line: 'ZSH_THEME="agnoster"'

- name: Set zsh plugins
  lineinfile:
    path: ~/.zshrc
    regexp: '^plugins='
    line: 'plugins=(git zsh-syntax-highlighting)'
    
- name: Set default user
  lineinfile:
    path: ~/.zshrc
    regexp: '^DEFAULT_USER='
    line: 'DEFAULT_USER=`whoami`'
